### ISSUE TITLE
vi cannot write file

### ISSUE THREAD

**Issue by LightChang** [Backblaze-B2-Samples/b2fs4chia#11]
when i create "hello.txt" for testing, it shows following error

2021-06-18 16:46:58,600:INFO:Access / (mode:1)
Traceback (most recent call last):
  File "/home/lightman/.local/lib/python3.8/site-packages/fuse.py", line 495, in _wrapper
    return func(*args, **kwargs) or 0
  File "/home/lightman/.local/lib/python3.8/site-packages/fuse.py", line 736, in create
    fi.fh = self.operations('create', path, mode)
  File "/home/lightman/.local/lib/python3.8/site-packages/fuse.py", line 800, in __call__
    return getattr(self, op)(*args)
  File "/home/lightman/.local/lib/python3.8/site-packages/b2fuse/b2fuse_main.py", line 325, in create
    raise NotImplementedError
NotImplementedError
Traceback (most recent call last):
  File "/home/lightman/.local/lib/python3.8/site-packages/fuse.py", line 495, in _wrapper
    return func(*args, **kwargs) or 0
  File "/home/lightman/.local/lib/python3.8/site-packages/fuse.py", line 736, in create
    fi.fh = self.operations('create', path, mode)
  File "/home/lightman/.local/lib/python3.8/site-packages/fuse.py", line 800, in __call__
    return getattr(self, op)(*args)
  File "/home/lightman/.local/lib/python3.8/site-packages/b2fuse/b2fuse_main.py", line 325, in create
    raise NotImplementedError
NotImplementedError
2021-06-18 16:46:58,606:INFO:Access / (mode:1)
2021-06-18 16:46:58,607:INFO:Access / (mode:1)
2021-06-18 16:46:58,609:INFO:Access / (mode:1)
2021-06-18 16:46:58,609:INFO:Access / (mode:1)
2021-06-18 16:46:58,984:INFO:Access / (mode:1)
2021-06-18 16:46:58,985:INFO:Access / (mode:1)
Traceback (most recent call last):
  File "/home/lightman/.local/lib/python3.8/site-packages/fuse.py", line 495, in _wrapper
    return func(*args, **kwargs) or 0
  File "/home/lightman/.local/lib/python3.8/site-packages/fuse.py", line 736, in create
    fi.fh = self.operations('create', path, mode)
  File "/home/lightman/.local/lib/python3.8/site-packages/fuse.py", line 800, in __call__
    return getattr(self, op)(*args)
  File "/home/lightman/.local/lib/python3.8/site-packages/b2fuse/b2fuse_main.py", line 325, in create
    raise NotImplementedError
NotImplementedError

**Comment by ppolewicz** [comment]
This specialized filesystem can only be read for reading and it's only usable for chia full proofs. All other usage is not supported. You may want to try https://github.com/sondree/b2_fuse which is a bit more generic

**Comment by LightChang** [comment]
roger that thank you
