### ISSUE TITLE
No module named 'importlib.metadata'

### ISSUE THREAD

**Issue by cloudminingpools** [Backblaze-B2-Samples/b2fs4chia#9]
from b2fs4chia /mnt/b2fs4chia --cache_timeout 3600

Traceback (most recent call last):
  File "/usr/local/bin/b2fs4chia", line 11, in <module>
    load_entry_point('b2fs4chia==0.1.7', 'console_scripts', 'b2fs4chia')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/b2fuse/b2fuse.py", line 31, in <module>
    from .version import VERSION
  File "/usr/local/lib/python3.6/dist-packages/b2fuse/version.py", line 26, in <module>
    from importlib.metadata import version
**ModuleNotFoundError: No module named 'importlib.metadata'**

**Comment by ppolewicz** [comment]
I think b2fs4chia may not work with python 3.6, it may be improperly labeled as compatible with 3.6 but it's a documentation error. Could you please try 3.7?
